### ISSUE TITLE
how to implement overlapping comments

### ISSUE THREAD

**Issue by NikhilPatel0019** [sereneinserenade/tiptap-comment-extension-react#1]
The issue I am facing is as follows: 
When I select a portion of text and add a comment to it, such as hello, the comment is added successfully. However, when I try to add a comment to another portion of text that includes the previously added comment, like another hello content, the comment associated with the "hello" text is removed. It appears that the span tag enclosing the "hello" text is being removed when adding the comment to the newly selected text.

**Steps to reproduce:**
1. Let's say we have the paragraph below:
`
Bali is predominantly a Hindu country. Bali is known for its elaborate, traditional dancing. The dancing is inspired by Hindi beliefs. Most of the dancing portrays tales of good versus evil. Watching the dancing is a breathtaking experience. Lombok has some impressive points of interest – the majestic Gunung Rinjani is an active volcano. It is the second-highest peak in Indonesia. Art is a Balinese passion. Batik paintings and carved statues make popular souvenirs.
`
2. No I select the text ```traditional``` and add a comment, this comment will be visible.
3. Now I select the text  ``` it's elaborate, traditional dancing``` and add a comment to it, this comment will be added too but commented added over the text ```traditional``` will be removed.

### Possible solution:
Need to figure out how to persist the span on already commented text when the given commented text is inside another text where the comment needs to be added.
```
renderHTML({ HTMLAttributes }) {
    return [
      'span',
      mergeAttributes(this.options.HTMLAttributes, HTMLAttributes),
      0,
    ]
  }
```

**Comment by sereneinserenade** [comment]
You're looking for https://prosemirror.net/docs/ref/#model.MarkSpec.excludes
